apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: ""
nameSuffix: ""

patches:
  - path: ../patches/namespace-patch.yaml
    target:
      kind: Deployment
      name: release-name-mongodb-sharded-mongos