apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-
nameSuffix: ""

patches:
  - path: namespace-patch.yaml
    target:
      kind: Deployment
      name: release-name-mongodb-sharded-mongos