apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mongo-test
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # image: arm64v8/alpine
          image: nginx
          ports:
            - containerPort: 80
