apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mongo-test
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: mongodb-init
          image: zwieratko/mongosh
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              export USERNAME=$(MONGO_INITDB_ROOT_USERNAME) 
              export PHRASE=$(MONGO_INITDB_ROOT_PASSWORD) 
              export URI="$(MONGODB_HOST):$(MONGODB_PORT)" 
              export MONGO_CONNECTION_STRING="mongodb://${USERNAME}:${PHRASE}@${URI}" 
              cd 
              mongosh --verbose --json=relaxed \
                  --eval 'show dbs' \
                  --eval 'db.adminCommand( { setFeatureCompatibilityVersion: "5.0" } )' \
                  ${MONGO_CONNECTION_STRING}              
              until echo 'db.stats()' | mongosh ${MONGO_CONNECTION_STRING}; do
                echo 'Waiting for MongoDB to become ready...'
                sleep 5
              done
              echo 'List of Databases' 
              echo 'show dbs' | mongosh ${MONGO_CONNECTION_STRING}/?authSource=admin
              echo 'Set FeatureCompatibility Version...' 
              echo 'db.adminCommand( { setFeatureCompatibilityVersion: "5.0" } )' | mongosh ${MONGO_CONNECTION_STRING}/?authSource=admin
              sleep 5 
              echo 'Verify FeatureCompatibility Version...' 
              echo 'db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )' | mongosh ${MONGO_CONNECTION_STRING}/?authSource=admin
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-express-configmap
                  key: database_url
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-express-configmap
                  key: database_port
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsGroup: 1000
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      containers:
        - name: backend
          # image: arm64v8/alpine
          image: nginx
          ports:
            - containerPort: 80
