apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: uplink
  labels:
    app: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          imagePullPolicy: Never
          image: mongodb
          ports:
            - containerPort: 27017
