apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mongo-test
  labels:
    app: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.0.10
          ports:
            - containerPort: 27017
