apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongo-test
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
