apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gzd2032/argocd-kubernetes-gitops-tutorial.git
    targetRevision: HEAD
    path: Charts/mongodb-sharded/charts/mongodb-sharded-8.0.8/mongodb-sharded/charts/common
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true