apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  labels:
    app: mongodb
spec:
  project: default
  source:
    repoURL: https://github.com/gzd2032/argocd-kubernetes-gitops-tutorial.git
    targetRevision: HEAD
    path: uplink/mongodb/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: uplink
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
