# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: mongodb-sharded
  repo: oci://registry-1.docker.io/bitnamicharts
  releaseName: mongodb-sharded
  namespace: mongo-sharded
  version: 8.0.8
  valuesFile: values.yaml