apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mongo-test
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: mongodb-init
          image: alpine/mongosh
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              export USERNAME=$(MONGO_INITDB_ROOT_USERNAME) 
              export PHRASE=$(MONGO_INITDB_ROOT_PASSWORD) 
              export URI="$(MONGODB_HOST):$(MONGODB_PORT)" 
              export MONGO_CONNECTION_STRING="mongodb://${USERNAME}:${PHRASE}@${URI}" 
              echo 'Set FeatureCompatibility Version...' 
              echo 'db.adminCommand( { listDatabases: 1})' | mongosh --verbose ${MONGO_CONNECTION_STRING}/?authSource=admin 
              echo 'db.adminCommand( { setFeatureCompatibilityVersion: "4.0" } )' | mongosh --verbose ${MONGO_CONNECTION_STRING}/?authSource=admin 
              sleep 5 
              echo 'Veriy FeatureCompatibility Version...' 
              echo 'db.adminCommand( { getParameter: 1, featureCompatibilityVersion: 1 } )' | mongosh --verbose ${MONGO_CONNECTION_STRING}/?authSource=admin
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-express-configmap
                  key: database_url
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-express-configmap
                  key: database_port
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
