apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

patches:
  - path: replicas-patch.yaml
    target:
      kind: Deployment
      name: frontend
